### ISSUE TITLE
[Feature request] Add enable/disable-toggle to individual capture sources

### ISSUE THREAD

**Issue by laurens94** [sabaatworld/HyperionScreenCap#33]
I have two monitors and each monitor has a Raspberry Pi which is running Hyperion.
Whenever I use monitor 0 and monitor 1 is not in use, Hyperion Screen Capture gives the following output in the logs and stops capturing:

```
2019-09-26 13:21:38 [INFO] [3] HyperionScreenCap.Helper.HyperionTask.InitScreenCapture:0 - HyperionTask[ConfigurationId: 800033]: Initializing screen capture
2019-09-26 13:21:38 [ERROR] [3] HyperionScreenCap.Helper.HyperionTask.StartCapture:0 - HyperionTask[ConfigurationId: 800033]: Exception in screen capture attempt: 29
System.Exception: Failed to initialize screen capture: HRESULT: [0x887A0002], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_NOT_FOUND/NotFound], Message: The object was not found. If calling IDXGIFactory::EnumAdaptes, there is no adapter with the specified ordinal.
 ---> SharpDX.SharpDXException: HRESULT: [0x887A0002], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_NOT_FOUND/NotFound], Message: The object was not found. If calling IDXGIFactory::EnumAdaptes, there is no adapter with the specified ordinal.

   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.Adapter.GetOutput(Int32 outputIndex)
   at HyperionScreenCap.DX11ScreenCapture.Initialize()
   at HyperionScreenCap.Helper.HyperionTask.InitScreenCapture()
   --- End of inner exception stack trace ---
   at HyperionScreenCap.Helper.HyperionTask.InitScreenCapture()
   at HyperionScreenCap.Helper.HyperionTask.StartCapture()
2019-09-26 13:21:38 [INFO] [3] HyperionScreenCap.Helper.HyperionTask.StartCapture:0 - HyperionTask[ConfigurationId: 800033]: Will re-initialize screen capture on retry
2019-09-26 13:21:38 [ERROR] [3] HyperionScreenCap.Helper.HyperionTask.StartCapture:0 - HyperionTask[ConfigurationId: 800033]: Max screen capture attempts reached. Giving up.
2019-09-26 13:21:38 [ERROR] [3] HyperionScreenCap.NotificationUtils.Error:0 - Error notification: Failed to initialize screen capture: HRESULT: [0x887A0002], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_NOT_FOUND/NotFound], Message: The object was not found. If calling IDXGIFactory::EnumAdaptes, there is no adapter with the specified ordinal.
```

A workaround now is to delete the capture source of monitor 1 and reconfigure it when I need it again.

Having a checkbox to enable/disable each capture source would fix this.

It could be placed left from the ID column:

![afbeelding](https://user-images.githubusercontent.com/5780704/65684486-0c56ad00-e060-11e9-8cf0-14f93b9c7dc3.png)

**Comment by laurens94** [comment]
Quick & dirty fix: change HyperionTask.cs line 168:

![afbeelding](https://user-images.githubusercontent.com/5780704/66499634-7b042380-eac0-11e9-8a45-b900ee3b633b.png)

**Comment by sabaatworld** [comment]
I have implemented this feature and code is pushed out. Will include in next release.

**Comment by sabaatworld** [comment]
New release is out now. Please open another issue if it does not work.
